### ISSUE TITLE
Patch utility crashes when run in Dosbox or other dos window

### ISSUE THREAD

**Issue by davidm71** [pinczakko/PCI-Expansion-ROM-OS#1]
Can't run the patch utility nor can I compile them from scratch. Tried compiling them inside ubuntu and GCC threw errors. Got a modded rom I can't wait to test out..

Thanks

**Comment by davidm71** [comment]
Learned how to compile with Mingw64. Case Closed.

**Comment by pinczakko** [comment]
Thanks for the notification.
